### PR TITLE
add trustServerCertificate if the parameter exists

### LINKED ISSUE #3572: Cannot Restore-BcDatabaseFromArtifacts because of SSL Provider issue
Hi. I can't restore a database from artifacts on my external SQL because of issue "SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted".

Regarding this issue: https://github.com/microsoft/SQLServerPSModule/issues/35 there is a switch `-TrustServerCertificate` in the SQLServer module. Can you add that switch to the `Restore-BcDatabaseFromArtifacts` script?

```
PS C:\Users\mkilinski> Restore-BcDatabaseFromArtifacts -artifactUrl (Get-BCArtifactUrl -type OnPrem -country w1 -version 24 -select Latest) -databaseServer SRV-SQL-01 -databasePrefix 'MKI-' -databaseName 'TEST'
Starting Database Restore job from https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/24.2.20227.20424/w1
C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.15\Import-BcContainerHelper.ps1
BcContainerHelper version 6.0.15
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.22621.2506
Downloading Artifacts https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/24.2.20227.20424/w1
Importing PowerShell module C:\bcartifacts.cache\onprem\24.2.20227.20424\platform\ServiceTier\program files\Microsoft Dynamics NAV\240\Service\Management\Microsoft.Dynamics.Nav.Management.dll
Restore-BcDatabaseFromArtifacts Telemetry Correlation Id: a3c22923-895d-4b9f-8b3e-0c7e4e93c71d
A connection was successfully established with the server, but then an error occurred during the login process. (provid
er: SSL Provider, error: 0 - Łańcuch certyfikatów został wystawiony przez urząd, którego nie jest zaufany.)
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.15\Bacpac\Restore-BcDatabaseFromArtifacts.ps1:222 c
har:13
+             $job | Receive-Job
+             ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlException
    + FullyQualifiedErrorId : SqlExceptionError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
    + PSComputerName        : localhost
```

### PR DESCRIPTION
**Pull request by freddydk**
Bump version
Fixes #3572

### CODE REVIEW

**Comment by rub7** [comment]
I have this same problem. Do you have a planned date for when this PR will be integrated? Than you

**Comment by freddydk** [comment]
Totally forgot about this - thought it was merged.
Will ask for a review.

**Review by mazhelez — APPROVED** [review]

**Comment by freddydk** [comment]
Should be included in the preview now.

**Comment by rub7** [comment]
It works! Thanks!

**Pull request merged**
