### PR TITLE
Look for a running "dockerd" process and not a running "docker" service to determine if docker is running

### PR DESCRIPTION
**Pull request by Sven-Niehus**
See issue #2237

### CODE REVIEW

**Comment by freddydk** [comment]
changing this would cause all other machines to fail:
image
I would rather like to know: How did you install docker? what SKU are you running?

**Comment by Sven-Niehus** [comment]
> changing this would cause all other machines to fail:

In the proposed change I'm looking for a Process called dockerd (```Get-Process "dockerd" -ErrorAction Ignore```) not for a Service with the name ```dockerd```. The process dockerd should be present on all machines, because the docker daemon needs to be running for everything with docker.

> I would rather like to know: How did you install docker? what SKU are you running?

As I'm on Windows Server I have installed docker via the binaries from [here](https://download.docker.com/win/static/stable/x86_64/) as you mentioned in [this](https://freddysblog.com/2021/10/30/docker-and-business-central/) blog post. After downloading the binaries I have installed the docker service via [nssm](https://github.com/kirillkovalenko/nssm) and named the service ```dockerd```

**Comment by freddydk** [comment]
good point, thanks

**Comment by freddydk** [comment]
This fix broke containerhelper tests.
The following lines checked the status on the dockerservice - and the process object doesn't have a status.
Not sure how the PR could ever work?

I have removed the following lines and resubmitted.

**Pull request merged**
