### PR TITLE
New Cmdlt New-AadAppsForBc using Microsoft.Graph

### PR DESCRIPTION
**Pull request by pri-kise**
I tried to add new cmdlet that supports the new Microsoft.Graph Powershell Module to create the Aad  Apps. (See issue https://github.com/microsoft/navcontainerhelper/issues/2351)

it can be tested with the following commands:
```ps
$bcAuthContext = New-BcAuthContext -tenantID $azureTenantId -clientID $azureApplicationId -clientSecret $clientSecret -scopes "https://graph.microsoft.com/.default"
  $AdProperties = New-AadAppsForBc -appIdUri https://mycontainer.mydomain/bc/ -bcAuthContext $bcAuthContext 
```
If there is anything that should be changed, I'm happy to do so. I'm no expert with powershell, therefore there can be some room for improvements.

### CODE REVIEW

**Comment by freddydk** [comment]
Thanks. I will go through this after Directions NA

**Comment by pri-kise** [comment]
@freddydk I'm really looking forward for your feedback on this new cmdlet that it'll be available before the [EOL of the  Azure AD API](
https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363) and that someone can find bugs and improve this cmdlt.

**Comment by freddydk** [comment]
Thanks - will do - I will need to be able to set aside a block of time for this.
Thanks a lot for your submission and rest assured that this will be fixed in good time before EOL of AAD API.

**Comment by freddydk** [comment]
Thanks, will try to get this done next week.

**Comment by pri-kise** [comment]
@freddydk just a short reminder for this PR. 
Maybe you'll find some time in the new year to take a look at this specific scenario to enable support the MS Graph API.

**Comment by freddydk** [comment]
I definitely will

**Comment by freddydk** [comment]
This PR fixes a few issues with the functions, which I ran into - and adds them to the exported functions.
https://github.com/microsoft/navcontainerhelper/pull/2996

It also adds a deprecation warning to the Create-AadAppsForBc.

Let me know if you find any issues with my changes.

**Comment by pri-kise** [comment]
@freddydk I've checked our source and we added the following to grant permission access to the new created application.

```ps
    $client = Get-MgServicePrincipal -Filter "appId eq '$appId'"
    $resource = Get-MgServicePrincipal -Filter "servicePrincipalNames / any(n: n eq 'https://graph.microsoft.com')"
    New-MgOAuth2PermissionGrant -ClientId $client.Id -ConsentType "AllPrincipals" -ResourceId $resource.Id
```
Maybe this can be simplified  or improved but I only want to the leave this here for reference.

**Comment by freddydk** [comment]
Thanks, so this will avoid that when I connect the first time, I need to consent?

**Comment by pri-kise** [comment]
Exactly. The first approval was very annoying for our developers and we wanted to avoid this step.
I don't know if the app registration (that we use for authentication) needs specific rights to perform this request.
See: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/new-mgoauth2permissiongrant?view=graph-powershell-1.0
Maybe the client id and the resource Id could retrieved more easily or save during the creation process and reused afterwards.

**Pull request merged**
