### PR TITLE
Added api.partner.microsoft.com scope

### PR DESCRIPTION
**Pull request by jonaswre**
Maybe I'm missing a curtial part of the documentation. 
But I didn't find any reference how to setup the authentication with app source.

There were 2 issues I had. 

1. The scope to use for the authentication
2. The way to authorize an app registration against the partner center. 

This change helps with 1. addtionally it might be helpful to mention it here as well https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md#appsource-specific-advanced-settings

If you tell me where to document the 2. issue I will do that.

### CODE REVIEW

**Comment by jonaswre** [comment]
Ok... I guess I was missing the right information.
Is there a rss feed for your blog?

**Comment by freddydk** [comment]
my blog is wordpress - I think https://freddysblog.com/feed/ would work.
Based on this error - I think I will also test whether scopes is correct in New-AlGoAppSourceContext - and give an error if not.

**Comment by jonaswre** [comment]
Thanks the feed is great. 

Wouldn't it be better to throw that error before the actual request? Or maybe do the request and show a warning that the scope might be wrong if you get an 401 response. Because the way you describe it in the AppSourceContext Setting I think lots of people will just write the context manually. (that's what I did at first.)

**Comment by freddydk** [comment]
You mean adding a check to the invoke-IngestionAPIRestMethod function - good idea.

**Pull request closed without merging**
