### PR TITLE
Add multitenant support for unpublish

### PR DESCRIPTION
**Pull request by gunnargestsson**
We need to add the -tenant parameter if we have a multitenant container running and the app has been installed into the tenant scope.

### CODE REVIEW

**Comment by freddydk** [comment]
Is the Scope on Get-NavAppInfo available on NAV 2018 as well?
The same code is running and need to be resilient to old versions and not crash

**Comment by gunnargestsson** [comment]
It is not but this code will not cause an error.

PS C:\Windows\system32> (Get-NAVAppInfo -ServerInstance DynamicsNAV110 -Name "Microsoft Pay Payments").Scope -eq "Tenant"
False

**Comment by freddydk** [comment]
With Set-StrictMode -versioin 2.0 and $errorActionpreference = Stop - I think it will cause an error

**Comment by gunnargestsson** [comment]
You are correct.

PS C:\Windows\system32> Set-StrictMode -version 2.0; $errorActionpreference = "Stop"
PS C:\Windows\system32> (Get-NAVAppInfo -ServerInstance DynamicsNAV110 -Name "Microsoft Pay Payments").Scope -eq "Tenant"
The property 'Scope' cannot be found on this object. Verify that the property exists.
At line:1 char:1
+ (Get-NAVAppInfo -ServerInstance DynamicsNAV110 -Name "Microsoft Pay P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

**Comment by freddydk** [comment]
ContainerHelper runs with strict mode 2 and error stop.
I have a lot of places, where I check for properties before reading them - if you can do the same, I will take the PR

**Comment by freddydk** [comment]
Needs to be -eq and not -match

**Comment by gunnargestsson** [comment]
$appInfo.PSObject.Properties.Name is an array of all the property names.  That is why I use -match

**Comment by freddydk** [comment]
-eq will do the same, but -match 'Scope' will also return true if 'ScopeEx' exists
Right now - that would not be a problem - but I have changed all occurances of -match to -eq all over because some property was added and something failed which I spend a lot of time fixing.

**Pull request merged**
