### PR TITLE
BCSaaS Environment Upgrade Handling

### PR DESCRIPTION
**Pull request by JulianSchmidtkeGWS**
Hi Freddy,

we would love to integrate more BC Admin Center API Requests into BCContainerHelper.

In this PR i start with Environment Upgrade Handling. You can check if a upgrade for an environment is scheduled by running Get-BcScheduledUpgrade and reschedule upgrades by running Reschedule-BcUpgrade.

The Functions use this API: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-center-api_reschedule_updates

I tried to copy the style of your other bcsaas functions :) 

Feedback is welcome!

### CODE REVIEW

**Comment by freddydk** [comment]
Thanks for this - Looks good - could you add two lines to the releasenotes.txt with info on the two functions.
+ we also need to add the functions to the BcContainerHelper.psd1 file.
The .psd1 file gets generated on publish, but there are also cases, where the module is imported by running the .ps1 file and for that purpose, the .psd1 file needs to be updated as well.

**Comment by JulianSchmidtkeGWS** [comment]
Hey Freddy,
i updated the releasenotes and the .psd1 file. Hope the version is correct like this

**Comment by freddydk** [comment]
Thanks
Sorry for not being specific, the ReleaseNotes should be under 3.0.12 (which is the version currently in preview).

**Comment by JulianSchmidtkeGWS** [comment]
Rebased and fixed the releasenotes

**Comment by freddydk** [comment]
Thanks

**Pull request merged**
