### PR TITLE
Add parameters scope and syncMode

### PR DESCRIPTION
**Pull request by ajkauffmann**
New parameters in Publish-NavContainerApp:

- scope - to enable publish and install as tenant extension, which is similar to how AL extension in VS Code works.
- syncMode - to enable Add, Clean or Development mode for database schema synchronization. The default sync mode used by VS Code is Development, to enforce database synchronization without increasing the version number of the app.

### CODE REVIEW

**Comment by freddydk** [comment]
Looks good, thanks

**Comment by kine** [comment]
After this merge, there is error when using the code>

**Comment by ajkauffmann** [comment]
My fault.... I was quickly redoing the changes after a clean clone of the repo. Saw Sync-..... and put the Mode in the wrong place.

**Comment by freddydk** [comment]
I have checked in a fix for this to make the new parameters optional instead of defaulted.

**Pull request merged**
