### PR TITLE
Sort-AppFoldersByDependencies AppId to Id

### PR DESCRIPTION
**Pull request by Spycoclown**
Microsoft changed in Al 4.1 the name of the tag AppId in the file app.json.
the structure changed:
```
"dependencies": [
      {
        "id": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
        "publisher": "Microsoft",
        "name": "System Application",
        "version": "1.0.0.0"
      }
}
```

### CODE REVIEW

**Comment by freddydk** [comment]
Won't this break this function when used on any pre-4.1 version?

**Comment by Spycoclown** [comment]
yes that is true, i just look for the best solution.

**Comment by Spycoclown** [comment]
i have to over work it. sry

**Comment by freddydk** [comment]
I will talk to the moderndev team and create a good solution, thanks for the heads up

**Comment by titofffffff** [comment]
hello,

I work on NAV 2018 and it's a breaking change for me...

Have you any workaround ?

Thank in advance for your help

**Comment by freddydk** [comment]
The fix I made should work for NAV 2018 and BC.
Please create a new issue with a repro script if you have an issue with this.

Thanks

**Pull request closed without merging**
