### PR TITLE
 Ignore $myScripts if necessary

### PR DESCRIPTION
**Pull request by waldo1001**

### CODE REVIEW

**Comment by freddydk** [comment]
Some of your changes are overwriting some changes I made
I have a auth parameter (not authenticationtype) you have changed that (I think unintentionally)
But you are right, that myScripts should have had a default value in new-navcontainer:
        [string[]]$additionalParameters = @(),
        [string[]]$myScripts = @()
I will check this in right away.
Please start a pull request from a fresh branch, thanks

**Comment by waldo1001** [comment]
It should not.  The total change of the pull request does not include that change.  On of the commits is merging your changes into my fork.. .

Sorry - didn't know how to do it, besides unfork an refork (may be I should have done that.. ).

**Comment by waldo1001** [comment]
Just look at the "Files Changed"
https://github.com/Microsoft/navcontainerhelper/pull/10/files

**Comment by waldo1001** [comment]
I'm unforking as we speak - next time a clean pull request... :-)

#sorry

**Comment by freddydk** [comment]
Fixed – and now with ReleaseNotes:

https://www.powershellgallery.com/packages/navcontainerhelper/0.1.1.8



/Freddy

Fra: waldo [mailto:notifications@github.com]
Sendt: 7. november 2017 09:34
Til: Microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Freddy Kristiansen <Freddy.Kristiansen@microsoft.com>; Comment <comment@noreply.github.com>
Emne: Re: [Microsoft/navcontainerhelper] Ignore $myScripts if necessary (#10)


I'm unforking as we speak - next time a clean pull request... :-)

#sorry

**Comment by freddydk** [comment]
OK, I need to learn some more about this as well:-)

**Pull request closed without merging**
