### PR TITLE
Update Get-NavContainerAppRuntimePackage.ps1

### PR DESCRIPTION
**Pull request by gunnargestsson**
App Name can contain unwanted file name characters

### CODE REVIEW

**Comment by freddydk** [comment]
I think there are a lot of places where this is an issue. Why wouldn't you just add the appfile parameter yourself?

**Comment by gunnargestsson** [comment]
I could, just wanted to contribute...  Your call

**Comment by gunnargestsson** [comment]
This is the only place I have found that gives me an error with my AppSource App.  Would appreciate if this can be merged.  Can't see that this will cause any problems.

**Comment by freddydk** [comment]
Ok

**Pull request merged**
