### PR TITLE
Add Traefik support

### PR DESCRIPTION
**Pull request by tfenster**
This allows creating a new NAV container with the necessary settings and labels for Traefik as explained here https://www.axians-infoma.com/techblog/running-multiple-nav-bc-containers-on-an-azure-vm/

With the PR in place you can create a new container reachable through Traefik as easy as this:

```
New-NavContainer -accept_eula -containerName imau -imageName mcr.microsoft.com/businesscentral/onprem:de -useTraefik
NavContainerHelper is version 0.0
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.4
Docker Server Version is 18.09.4
Using image mcr.microsoft.com/businesscentral/onprem:de-ltsc2019
PublicDnsName is traef-test10.westeurope.cloudapp.azure.com
Creating Nav container imau
Version: 14.0.29537.0-de
Platform: 14.0.29530.0
Generic Tag: 0.0.9.5
Container OS Version: 10.0.17763.437 (ltsc2019)
Host OS Version: 10.0.17763.437 (ltsc2019)
Using process isolation
Add specific CheckHealth.ps1 to enable Traefik support
Creating container imau from image mcr.microsoft.com/businesscentral/onprem:de-ltsc2019
5fd76cff1c74cfb316742dd33bfbf0a4707bc7bb58b8a90d18bc974206e79a64
Waiting for container imau to be ready
Initializing...
Starting Container
Hostname is traef-test10
PublicDnsName is traef-test10.westeurope.cloudapp.azure.com
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting PublicODataBaseUrl to https://traef-test10.westeurope.cloudapp.azure.com/imaurest
Setting PublicSOAPBaseUrl to https://traef-test10.westeurope.cloudapp.azure.com/imausoap
Setting PublicWebBaseUrl to https://traef-test10.westeurope.cloudapp.azure.com/imau/
Starting Service Tier
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user vmadmin
Setting SA Password and enabling SA
Creating SUPER user
Registering event sources
Container IP Address: 172.23.78.199
Container Hostname  : traef-test10
Container Dns Name  : traef-test10.westeurope.cloudapp.azure.com
Web Client          : http://traef-test10.westeurope.cloudapp.azure.com/imau/
Dev. Server         : http://traef-test10.westeurope.cloudapp.azure.com
Dev. ServerInstance : NAV

Files:
http://traef-test10.westeurope.cloudapp.azure.com:8080/al-3.0.106655.vsix

Initialization took 82 seconds
Ready for connections!
Reading CustomSettings.config from imau
Creating Desktop Shortcuts for imau
Nav container imau successfully created
Because of Traefik, the following URLs need to be used when accessing the container from outside your Docker host:
Web Client:        https://traef-test10.westeurope.cloudapp.azure.com/imau/
SOAP WebServices:  https://traef-test10.westeurope.cloudapp.azure.com/imausoap
OData WebServices: https://traef-test10.westeurope.cloudapp.azure.com/imaurest
Dev Service:       https://traef-test10.westeurope.cloudapp.azure.com/imaudev
File downloads:    https://traef-test10.westeurope.cloudapp.azure.com/imaudl
```

### CODE REVIEW

**Comment by freddydk** [comment]
2 comments

This file: $myscripts += "c:\traefikforbc\my\CheckHealth.ps1" - would not exist on most machines. I think the CheckHealth.ps1 needs to be added to navcontainerhelper and use PSScriptRoot.

When grabbing PublicDnsName from hostname.txt you should only do that if $publicDnsName wasn't set specifically as a parameter to new-navcontainer.

With this, I will take this - and I guess we can make the nav-arm-templates just use this then

**Comment by tfenster** [comment]
I've added the check if PublicDnsName was provided as param

For the HealthCheck.ps1: My intention was to expect some things already in place like a working Traefik config, the Traefik container and so on, including the HealthCheck.ps1 (see https://github.com/tfenster/nav-arm-templates/blob/master/initialize.ps1#L191-L214). I am not sure if I like the idea that if someone just uses -useTraefik for New-NavContainer to the do all those things. I could check if everything is in place and then maybe point to something like "Initialize-TraefikForNavContainer" if something is missing?

**Comment by freddydk** [comment]
I think we should include the check and avoid fixed paths (if possible). Probably add checkhealth in containerhelper - and then include a function to create the container.

Wouldn't Setup-TraefikContainerForNavContainers be a better name?

**Comment by tfenster** [comment]
I'll give it a try

**Comment by tfenster** [comment]
I've implemented Setup-TraefikContainerForNavContainers, added the traefik files here and moved the files on the target machine to c:\programdata\navcontainerhelper. I've also adjusted the ARM template script accordingly. Let me know if this looks ok for you and I'll start testing

**Comment by freddydk** [comment]
Looks good
In nav-arm-templates - SetupNavContainer - I would keep one New-NavContainer and just use 

-useTraefik:($AddTraefik -eq "Yes") `

or add useTraefik to $params to avoid the fork.
Thanks

**Comment by tfenster** [comment]
Didn't know that works, cool and thanks. I'll give it a try and see if it all works together

**Comment by freddydk** [comment]
Stumbled over your change with CustomNavSettings in SetupNavContainer - I cannot imagine that that works???

**Comment by tfenster** [comment]
It worked in that state https://github.com/microsoft/nav-arm-templates/pull/100/commits/d4df3b5a9081f3291904772bb2f591ff50fab8d3 but I forgot to revert that one. Will do that, thanks

**Comment by tfenster** [comment]
@freddydk Now everything works for me: Initial setup creates the traefik files and container and configures the first container to use it. Further containers also work if -useTraefik is used

**Comment by freddydk** [comment]
Very cool, will review, merge and run my containerhelper tests

**Pull request merged**
