### PR TITLE
GetSymbolsUsingApp.json

### PR DESCRIPTION
**Pull request by NAVFreak**
This deals with issues:
[https://github.com/Microsoft/nav-docker/issues/325#issuecomment-460238675](https://github.com/Microsoft/nav-docker/issues/325#issuecomment-460238675)
[https://github.com/Microsoft/navcontainerhelper/issues/325](https://github.com/Microsoft/navcontainerhelper/issues/325)

The major problem is that you get different symbols when downloading in VS code  and using Compile-AppInNavContainer, it should be the same.

The problem is appearing when you have these settings in app.json and are using a newer docker image:
```
  "platform": "13.0.0.0",
  "application": "13.0.0.0",
```

If you use image 'mcr.microsoft.com/businesscentral/onprem:se' and download sysmbols you se the following in the terminal:
```
[2019-02-19 08:40:15.97] Sending request to http://dockermall:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0
[2019-02-19 08:40:15.99] Sending request to http://dockermall:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0
```  
And you get the files:
_Microsoft_Application_13.0.27183.0.app
Microsoft_System_13.0.12929.0.app_

Now delete the symbol files in .alpackages folder, copy your app folder to your docker container:
_C:\ProgramData\NavContainerHelper\Extensions\$ContainerName\my_

```
$Containername = '<ContainerName>'
$UserName = '<UserName>'
$PassWord = '<Password>'
$Credential = (New-Object System.Management.Automation.PSCredential($UserName,(ConvertTo-SecureString $PassWord -AsPlainText -Force)))
Compile-AppInNavContainer -containerName $ContainerName `
    -appProjectFolder "C:\ProgramData\NavContainerHelper\Extensions\$Containername\my\App" `
    -appOutputFolder "C:\ProgramData\NavContainerHelper\Extensions\$Containername\my" `
    -UpdateSymbols `
    -credential $Credential

```
Now go to the app folder och look the symbols in the folder:
_C:\ProgramData\NavContainerHelper\Extensions\DockerMall\my\App\.alpackages_
You get the files:
_Microsoft_Application_13.3.27233.0.app
Microsoft_System_13.0.12929.0.app_

### CODE REVIEW

**Comment by freddydk** [comment]
I think the change is correct - but a few comments.

Reformatting source code should not be done as part of a bugfix - makes it harder to see what has changed and what not.

There is something wrong in the fix.
$Version is undefined - meaning that it will of course be -ne $appVersion and -ne $platformversion.
and the code will never hit the "old" line. I think the right fix is to always to with the info in app.json.

**Comment by NAVFreak** [comment]
Ohh, I didn't think about the reformatting :(  
Ran it just to make sure my code was properly pasted in.

Isn't $version assigned on line 113..118?
```
$app = $publishedApps | Where-Object { $_.publisher -eq $publisher -and $_.name -eq $name }
if ($app) {
    $version = $app.version
}
```
There is one thing missing though and that is the correct name of the symbol file. As we have seen we ask for symbol to a certain version (13.0.0.0) but can ge gived another version. This fix doesn't handle that. A proper fix would have been to open up the symbol package and extract it from the NavxManifest.xml. I gave it a quick try and it seems to have 7-zip installed in order to unpack it.

**Comment by freddydk** [comment]
My bad on the $version - you are right.
Must be tired - will make another pass on this tomorrow.

**Comment by freddydk** [comment]
I have checked in a fix, which uses the info in app.json when requesting symbols and uses the info from published apps to give the file name. It will also find the app version number in the database if an app isn't published.
And finally - new-navcontainer will unpublish symbols when running hybrid development.
All of this should fix this issue.

**Pull request closed without merging**
