### PR TITLE
Remove-NAVServerUser fix while Invoking CodeUnits

### PR DESCRIPTION
**Pull request by vvkjndl**
Hi Freddy,

With BC19 release, Invoke-NavContainerCodeunit.ps1 is now throwing an error on Line#73 (Remove-NAVServerUser).

I am not sure why do we need to remove the `user manager\containeradministrator` user in the first place. We can just choose to keep the user and disable it when it's not needed.

With this PR, I am eliminating the Remove-NAVSeverUser command altogether while fixing the Set-NAVServerUser at the end of CodeUnit execution.

Also, before the CodeUnit execution starts, I am setting the user's company as passed in parameters, just in case it's significant.

**Error in BC19:**
```
WARNING: Import Successful
You must choose a company before you can access the "User Login" table.
at <ScriptBlock>, <No file>: line 28
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at Invoke-NavContainerCodeunit, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ObjectHandling\Invoke-NavContainerCodeunit.ps1: line 46
at global:Install-DemoDataPack, C:\Users\azure-admin\Desktop\SCRIPTS\SIMPMgmt.ps1: line 2810
at <ScriptBlock>, C:\Users\azure-admin\Desktop\SCRIPTS\Makefiles\SIP Makefiles\demo.inecta.com\SIPS\Make-TC.ps1: line 28
at <ScriptBlock>, <No file>: line 1
You must choose a company before you can access the "User Login" table.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ContainerHandling\Invoke-ScriptInNavContainer.ps1:45 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (You must choose...r Login" table.:String) [], RuntimeException
    + FullyQualifiedErrorId : You must choose a company before you can access the "User Login" table. 
```

**Warning in BC18:**
```
WARNING: Import Successful
WARNING: The user 'user manager\containeradministrator' cannot be removed because the user has been logged on to the system. Instead the user has been disabled.
```

### CODE REVIEW

**Comment by freddydk** [comment]
Thanks Vivek - I was looking at this today as well, but it seems you beat me to it.

**Comment by freddydk** [comment]
It looks like with this fix, it works the second time you call Invoke-codeunit

**Comment by vvkjndl** [comment]
For me, the fix works in the first attempt.

Are you doing Remove-Module and then re-importing BcContainerHelper?

**Comment by freddydk** [comment]
For me it seemed to be a race condition - had to wait for a second after creating the user.
I have changed the code a bit and checked in - it is building a new containerhelper now.

**Comment by freddydk** [comment]
and btw - I never install the containerhelper module - I always run the containerhelper ps1 directly (which removes and imports) - so every session has its own version of the module

**Comment by vvkjndl** [comment]
Thanks much Freddy for taking care of this. I have tested your latest changes and we are good. :)

**Comment by freddydk** [comment]
Thanks
If all tests pass - approx. one more hour.
Else - later today.

**Comment by freddydk** [comment]
https://www.powershellgallery.com/packages/BcContainerHelper/2.0.18-preview507

**Pull request merged**
