### PR TITLE
Add ci/cd workshop in Markdown format

### PR DESCRIPTION
**Pull request by TheNCuber**
Provide a starting point for future improvements of the ci/cd hands on lab.
Converted current version of the workshop pdf available at [aka.ms/cicdhol](https://aka.ms/cicdhol) as of May 1st 2021.

#1648

### CODE REVIEW

**Comment by freddydk** [comment]
Thanks a million Noah - I will run through this next week and modify the https://aka.ms/cicdhol

**Comment by freddydk** [comment]
Hi @TheNCuber 

I moved the repo here: https://github.com/microsoft/AL-Go/blob/main/Scenarios/old/CI_CD_Workshop.md
I also updated https://aka.ms/cicdhol to point to this location.
Reason for the movement is that all the images and the workshop is "normally" part of BcContainerHelper and will be 

Note that AL-Go for GitHub is the "new" way of doing DevOps.

**Comment by BW-PA** [comment]
Hi Freddy, with the official release of AL-GO at the beginning of April and the moving of the HOL workshop to scenarios/old will there be an associated blog post on AL-GO as a replacement for the CICDHOL?  Am I right in presuming that the Scenarios in AL-GO are in fact the replacement for CICDHOL?

**Comment by freddydk** [comment]
Yes.
Scenario no. 1 (+ a few of the others) is more or less the full CI/CD HOL.
And yes, there will be a series of blog posts - also on how to migrate from a repo created based on the CI/CD HOL to AL-Go for GitHub.

**Pull request merged**
