### PR TITLE
Set-BcContainerServerConfiguration and Restart-BcContainerServiceTier added

### PR DESCRIPTION
**Pull request by DanielGoehler**
I added the `Set-BcContainerServerConfiguration` and `Restart-BcContainerServiceTier` cmdlets to make it easier to change the Service Tier configuration.

### CODE REVIEW

**Comment by freddydk** [comment]
Quick you are:-)

Please add "| Out-Null" after both Invoke-script commands (after the argumentlist) to avoid any un-intended output.
And move the releasenotes to 3.0.9 (which hasn't been released yet, so this will be included in that)

**Comment by freddydk** [comment]
on 5. - when running with usepssession = $false - all output in the script (also output to host) will be added to the return value.
Hence | Out-Null is the safe bet.

**Comment by DanielGoehler** [comment]
Thanks. Done.

**Comment by DanielGoehler** [comment]
Someting went wrong let me try again.

**Pull request closed without merging**
