### PR TITLE
Dependency graph

### PR DESCRIPTION
**Pull request by jonaswre**
I need an up to date master. And because the decision on #2646 is still open I had create a new PR. Sorry for that... 

I finally had the time to integrate the functions I was speaking of in https://github.com/microsoft/navcontainerhelper/issues/2574.

The Get-DependencyGraph creates a dependency graph that can be used to query dependencies and dependents for diffrent appIds in diffrent versions.

Examples are provided in Tests\DependencyGraph.Tests.ps1

### CODE REVIEW

**Comment by jonaswre** [comment]
Maybe this should be part of the new bchelper module? Only dependency here is Get-BcContainerAppInfo

**Comment by freddydk** [comment]
Probably a good idea

**Comment by freddydk** [comment]
I think we should take this function and the other AzureFeed functions and place in a module called BC.AzureFeed or something like that. For now, you can have a dependency on BcContainerHelper - and when I am done splitting up containerhelper in smalller modules, you can change the dependency to the actually needed modules.

Make sense?

**Comment by jonaswre** [comment]
And regarding Azure Feed I think it should be deprecated. I don't see any reason to use if you can use nuget. The way dependencies are resolved is pretty slow because there is no easily readable metadata. You need to download the app and extract it until you are able to resolve the next. Plus the disadvantage that you can't use the fourth digit of your version number. 

Migration should be pretty easy, just download all packages from azure feed and upload them to nuget. By the way it would be cool to have an option to batch upload apps to a nuget feed (Github Packages). I've created an action that takes a url and uploads it to github packages but since you can't create nuget packages from runtimes it pretty useless for uploading thirdparty apps.

**Comment by jonaswre** [comment]
@freddydk I think this is still needed? 

I found it useful for walking the whole dependency tree. But if you think this is not need I would close the PR.

**Comment by freddydk** [comment]
I kept the PR in case we needed the functionality in other BCCH functions, but I don't think we do.
All accepted PRs comes with a support tax - probably not a lot, but still I would need to know the details of this code.
You could create another Gallery module called BC.DependencyGraph or like - if you would like to ship this.
Thanks for the contribution though

**Pull request closed without merging**
