### PR TITLE
AppFile variable does not exists in context

### PR DESCRIPTION
**Pull request by epernst**
Just a small change.

When using the Sync-NavContainerApp function, then it currently writes "Synchronizing $appFile on $tenant", which results in either blank or potential wrong information.

### CODE REVIEW

**Comment by epernst** [comment]
Didn't know additional pushes to my fork resulted in my pull request being updated. But then again why would it be different than with Azure DevOps.
Second push is merely what I referred to in https://github.com/microsoft/navcontainerhelper/issues/760#issue-528704851 issue. I have missed ForceRefresh in Get-NavContainerTenants.
And why limit the function to MultiTenant implementations, when its just as useful whenbit's not?
So I removed the error it not multi-tenant.

**Comment by freddydk** [comment]
Are you sure that this works?
You do not have a Param($Params) in the invoke-script scriptblock. I would assume that the parameter won't get transferred.
Also no parameter description is included in the file.

**Comment by epernst** [comment]
Oh yes, (param) was missing. Which is why you should not do refactoring right before submitting - the params was inside the invoke - but moving it outside it becomes easier to debug.
Also updated parameter docs.

**Comment by freddydk** [comment]
Thanks Erik

**Pull request merged**
