### PR TITLE
Check that WebClientPort and FileSharePort are different

### PR DESCRIPTION
**Pull request by jwikman**
Prevent the messup in #617 to happen again :)

### CODE REVIEW

**Comment by freddydk** [comment]
I guess run-tests and get-tests would also have to use the webclientport right?

**Comment by freddydk** [comment]
This fix would cause FileSharePort to always be set (due to the defaulting) - not sure there would be any problem with that, but it is a difference.
Examle - if somebody is using additionalparameters to set the fileshareport - that script would now fail.

**Comment by jwikman** [comment]
That's true, maybe that was my real problem yesterday? That the test used port 80, no matter what port I configured for the webclient? I couldn't find any relevant references to port 80, where is this set for the test functions?

Aah, now I understand why there were no default values for the parameters. I'll update the PR so the tests works without defaulting the parameter. 

But I guess that it'll still be an issue with additionalparameters. They'll be a bit of a challenge to test,  even if not impossible. Do you think we need to take that into consideration? I guess we have to...

**Comment by freddydk** [comment]
A fix like this in SetupVariables:
```
if ("$fileSharePort" -eq "")          { 
    if ($webClientPort -eq "8080") {
        $httpSite = "N"
    }
    else {
        $fileSharePort = "8080"
    }
}
```
would mean that the container would switch off the fileshare if you use webclientport = 8080 without setting the fileshareport.
Beside that - run and gettests should use the webclient port.
will fix these things.

**Comment by jwikman** [comment]
Yes, that is a better solution. 👍

**Comment by freddydk** [comment]
But thanks for finding this

**Pull request closed without merging**
