### PR TITLE
Using SqlServer PS module to load the Smo libraries

### PR DESCRIPTION
**Pull request by kine**
Solve #1800

### CODE REVIEW

**Comment by freddydk** [comment]
Very nice, have been thinking about this.

It does however break the code for those who has SQL installed and not SqlServer (like me)
If you could modify the code to do:

```
Import-Module sqlps -ErrorAction SilentlyContinue
$sqlModule = get-module sqlps
if ($sqlModule) {
    $smoServer = New-Object Microsoft.SqlServer.Management.Smo.Server $databaseServerInstance

    #load libraries the old way

}
else {
    Import-Module SqlServer -ErrorAction SilentlyContinue
    $sqlModule = get-module SqlServer
    if ($sqlModule) {
        
        # load libraries the new way

    }
    else {
        throw "You need to have a local installation of SQL or you need the SqlServer PowerShell module installed"
    }
}
```

**Comment by kine** [comment]
Have added line to remve the resolver else the job ends with error.

**Comment by freddydk** [comment]
It looks like smoServer is used in the codepath still and never set

**Comment by freddydk** [comment]
smoserver is used in line 90
New-NAVDatabase -DatabaseServer $databaseServer -DatabaseInstance $databaseInstance -DatabaseName $dbName -FilePath $bakFile -DestinationPath (Join-Path $smoServer.RootDirectory "DATA\$($databaseprefix -replace '[^a-zA-Z0-9]', '')") | Out-Null

**Comment by kine** [comment]
Ok, will check that, I have overlooked that. We can get the path in other way I think...

**Comment by kine** [comment]
Which path it should be? Path where the database should be restored? It means default path for databases on the server?

**Comment by freddydk** [comment]
If not specified (and restoring on own server) - it tries to use the path in the .bak file:-(
That is the reason for the construct.
Maybe it works with a relative path - I can test that, stay tuned

**Comment by kine** [comment]
I have used t-sql to get the default data path from the SQL. Can you try with that?

**Comment by kine** [comment]
I have stopped to use the New-NAVDatabase because it is not renaming the db files to new database names thus possible overwrite on the server when multiple databases are restored and the target will be same folder. Now I am using Restore-SqlDatabase with RelocateFile parameter.

**Comment by freddydk** [comment]
should be this: 
-DestinationPath (Join-Path $DefaultDataPath ($databaseprefix -replace '[^a-zA-Z0-9]', ''))

but you need the import-modules before you use invoke-sqlcmd (on my machine it fails otherwise)

**Comment by kine** [comment]
hmmm, no need for import-module on my. What it is missing on yours? 

I have different problem - it wants to restore to path where the prefix is subfolder but this doesn't exists on the server, thus restore fails (it needs to have this folder already existing).

**Comment by kine** [comment]
Ok, fixed the import-module issue, now I am importing the modules before getting the default path.

Still there is problem when the target path doesn't exists, but I think it was same even in original version.

**Comment by freddydk** [comment]
could  you remove the second 

```
if ($sqlmodule) {
```
and
```
                else {
                    throw "You need to have a local installation of SQL or you need the SqlServer PowerShell module installed"
                }
```

**Comment by freddydk** [comment]
The reason is that sqlps is not in the modules folder and is not automatically imported upon usage.
The other modules gets automatically loaded when you use them the first time.

**Comment by freddydk** [comment]
Thanks Kamil - great addition to the function.

**Pull request merged**
