### PR TITLE
Added support for "Version" in sync, publish, install & uninstall Nav…

### PR DESCRIPTION
**Pull request by hemisphera**
Installing multiple versions of the same app does not seem to be supported. So now "Publish-NavContainerApp" reads the version from the app and passes it along to Sync / Install. Synch / Install / and UnInstall-NavContainerApp now support an optional parameter "appVersion".

### CODE REVIEW

**Comment by freddydk** [comment]
This seems to be a breaking change.
Everybody with scripts will have to add appVersion as it is madatory.
The parameter will need to be made optional - and only transferred to the underlying functions if specified.
Thanks

**Comment by hemisphera** [comment]
I don't think this is a breaking change. The new parameters I have introduced are **not** mandatory.

You are correct though, that they are always transferred to the underlying function. But if they are not specified, they will be transferred as `$null` and the underlying functions already handle that case correctly.

**Comment by hemisphera** [comment]
I have just tested this and it works. The app "test" I am synchronizing below doesn't even exist. So the cmdlet seems to be pretty forgiving ...

image

I just wanted to avoid duplicating code, but if you prefer, I will change it to an if-else block.

**Comment by freddydk** [comment]
I prefer a construct like this:

```
$params = @{ }
if ($version) {
  $params += @{ "version" = $version }
}
sync-navapp nav -name $name @params
```

/Freddy

**Comment by freddydk** [comment]
Thanks, will include this.

**Pull request merged**
