### PR TITLE
Get-BCArtifactUrl

### PR DESCRIPTION
**Pull request by waldo1001**
As promised - based on the API.

I didn't look into the bcinsider-part (yet).

### CODE REVIEW

**Comment by freddydk** [comment]
Thanks
2 questions
What does it return if you specify All?
You have a limit=10 - is that on purpose? doesn't that mean that you will never get the US blob?

**Comment by waldo1001** [comment]
Sorry - the limit=10 was a test that didn't work - it was still in my code.  I removed it.
All will return all possible urls within the current filter.  While latest will obviously return only the latest one...

**Comment by freddydk** [comment]
for insider (and private artifacts store) support - I would rename the storageaccountname parameter to storageaccount - and if the storageaccount value doesn't have a . in it - add .azureedge.net - else keep as is (allows for embed partners to create a storage account with apps, pointing to MS platforms).

also - add a parameter called sasToken (default ""). If not "" - add that to the URL (before adding the other parameters - and add the other parameters with an & instead of ?) - this is the way insider sas tokens are shared on collaborate.

**Comment by freddydk** [comment]
This is very cool:-)

**Comment by waldo1001** [comment]
Should the sasToken from the document work?

**Comment by freddydk** [comment]
The statement on SasToken above is wrong - it cannot just be added to the rest request.
I still think we want the full SasToken as a parameter, but the shared access key needs to be extracted and added in the request part.
I am happy to take this part if you don't have time?

**Comment by waldo1001** [comment]
Thanks for documentation link.
I don't mind to give this a go ... .  I'll report back on monday!

**Comment by waldo1001** [comment]
@freddydk , I included the sasToken.  Looking forward to your feedback

**Comment by freddydk** [comment]
Did it work like that? I thought it wouldn't

**Comment by waldo1001** [comment]
It did - I needed to provide the resource type (&restype=container)

**Comment by freddydk** [comment]
Cool - will test tonight

**Comment by freddydk** [comment]
Thanks Waldo

**Comment by waldo1001** [comment]
Very welcome :-).

**Comment by freddydk** [comment]
Found a few issues, have fixed them myself, will checkin tomorrow

**Comment by waldo1001** [comment]
Wow .. hardly recognizable :-). Nice!

**Pull request merged**
